#!/bin/bash

yay -Sy neovim\
    cmake\
    fzf\
    wemeet-bin\
    clangd\
    python\
    lua\
    gcc\
    tree\
    cuda\
    git\
    gcc\
    python\
    vulkan-devel\
    glm\
    linuxqq\
    wemeet-bin\
    uxplay\
    obs\
    thunderbird\
    musescore\
    microsoft-edge-stable\
    aarch64-linux-gnu-gdb\
    aarch64-linux-gnu-glibc\
    acpi\
    acpid\
    adobe-source-han-sans-cn-fonts\
    adobe-source-han-sans-jp-fonts\
    adobe-source-han-sans-kr-fonts\
    adobe-source-sans-fonts\
    alsa-firmware\
    alsa-utils\
    amd-ucode\
    android-tools\
    appmenu-gtk-module\
    arc-icon-theme\
    arduino\
    argparse\
    ark\
    arm-none-eabi-gcc\
    arm-none-eabi-gdb\
    arm-none-eabi-newlib\
    autoconf\
    automake\
    autotiling\
    avahi\
    b43-fwcutter\
    baidunetdisk-bin\
    bash\
    bash-language-server\
    bat\
    biber\
    bison\
    bluedevil\
    bluez-utils\
    boost\
    breeze-gtk\
    btrfs-progs\
    bzip2\
    certbot\
    cmake\
    code-minimap\
    codelldb-bin\
    coreutils\
    cpupower\
    cronie\
    cryptsetup\
    cuda\
    cudnn\
    dconf-editor\
    ddcutil\
    debtap\
    debugedit\
    deepin-wine-qq\
    deepin-wine-wechat\
    device-mapper\
    dhclient\
    dhcpcd\
    dialog\
    diffutils\
    dingtalk-bin\
    dmidecode\
    dmraid\
    dnsmasq\
    docker\
    dolphin\
    dolphin-plugins\
    dosfstools\
    dotnet-sdk\
    dpkg\
    e2fsprogs\
    ecryptfs-utils\
    efibootmgr\
    eigen\
    elisa\
    exfatprogs\
    f2fs-tools\
    fcitx\
    fcitx-configtool\
    fcitx-qt5\
    fcitx-qt6\
    fcitx-sogoupinyin\
    fd\
    feh\
    ffmpeg\
    ffmpegthumbs\
    file\
    filelight\
    filesystem\
    filezilla\
    findutils\
    firefox\
    fish\
    flex\
    freerdp\
    frpc\
    fwupd\
    fzf\
    gawk\
    gcc-libs\
    geogebra\
    gettext\
    gitlab\
    glfw-x11\
    glibc\
    glibc-locales\
    glm\
    glow\
    gnome-themes-extra\
    gnu-netcat\
    gradle\
    grep\
    grub\
    grub-btrfs\
    grub-theme-manjaro\
    gst-libav\
    gst-plugins-bad\
    gst-plugins-base\
    gst-plugins-good\
    gst-plugins-ugly\
    gtest\
    gtk3\
    gufw\
    gwenview\
    gzip\
    haveged\
    helix\
    htop\
    inetutils\
    inxi\
    iproute2\
    iputils\
    iverilog\
    jdk11-openjdk\
    jdk8-openjdk\
    jdtls\
    jfsutils\
    jre17-openjdk\
    kaccounts-providers\
    kamera\
    kate\
    kcalc\
    kde-gtk-config\
    kdeconnect\
    kdegraphics-thumbnailers\
    kdenetwork-filesharing\
    kdeplasma-addons\
    keditbookmarks\
    kfind\
    kgamma5\
    khelpcenter\
    khotkeys\
    kimageformats\
    kinfocenter\
    kinit\
    kio-extras\
    kmenuedit\
    konsole\
    kscreen\
    kscreenlocker\
    ksshaskpass\
    ksysguard\
    ksystemlog\
    kwallet-pam\
    kwalletmanager\
    kwayland-integration\
    kwin\
    kwrited\
    latex-mk\
    latte-dock\
    lazygit\
    less\
    lib32-gconf\
    lib32-libcanberra\
    lib32-libva-intel-driver\
    lib32-libva-mesa-driver\
    lib32-libva-vdpau-driver\
    lib32-mesa-demos\
    lib32-nvidia-utils\
    libcanberra\
    libdvdcss\
    libpamac-flatpak-plugin\
    libva-intel-driver\
    libva-mesa-driver\
    libva-vdpau-driver\
    licenses\
    linux515\
    linux515-nvidia\
    linuxqq\
    logrotate\
    lolcat\
    lua\
    lua-cjson\
    lua-language-server-git\
    luarocks\
    lvm2\
    lxappearance\
    maim\
    make\
    man-db\
    man-pages\
    manjaro-alsa\
    manjaro-application-utility\
    manjaro-browser-settings\
    manjaro-documentation-en\
    manjaro-firmware\
    manjaro-hello\
    manjaro-hotfixes\
    manjaro-kde-settings\
    manjaro-printer\
    manjaro-pulse\
    manjaro-release\
    manjaro-settings-manager-kcm\
    manjaro-settings-manager-knotifier\
    manjaro-system\
    manjaro-zsh-config\
    matray\
    mdadm\
    memtest86+\
    mesa-demos\
    mhwd\
    mhwd-db\
    microsoft-edge-stable-bin\
    milou\
    mkcert\
    mkinitcpio-openswap\
    mobile-broadband-provider-info\
    modemmanager\
    mono-msbuild\
    mpv\
    mtpfs\
    multicolor-sddm-theme\
    musescore\
    nano\
    nano-syntax-highlighting\
    neofetch\
    neovide\
    neovim\
    net-tools\
    netease-cloud-music\
    network-manager-applet\
    networkmanager\
    networkmanager-l2tp\
    networkmanager-openconnect\
    networkmanager-openvpn\
    networkmanager-pptp\
    networkmanager-vpnc\
    nfs-utils\
    nginx-mainline\
    nmap\
    noto-fonts\
    noto-fonts-emoji\
    npc\
    nps\
    nss-mdns\
    ntfs-3g\
    ntp\
    numlockx\
    nvidia-utils\
    obs-studio\
    okular\
    opendoas\
    openocd\
    openresolv\
    openssh\
    os-prober\
    oxygen\
    oxygen-icons\
    p7zip\
    packagekit-qt5\
    pacman\
    pamac-cli\
    pamac-gtk\
    pamac-tray-icon-plasma\
    pandoc\
    partitionmanager\
    patch\
    pciutils\
    pcmanfm\
    perl\
    perl-file-mimeinfo\
    pgyvpn-bin\
    phonon-qt5-gstreamer\
    pkgconf\
    plasma-browser-integration\
    plasma-desktop\
    plasma-nm\
    plasma-pa\
    plasma-simplemenu\
    plasma-systemmonitor\
    plasma-workspace\
    plasma-workspace-wallpapers\
    poppler-data\
    powerdevil\
    powertop\
    prettier\
    prince-bin\
    print-manager\
    procps-ng\
    psmisc\
    pulseaudio-bluetooth\
    pulseaudio-ctl\
    pulseaudio-zeroconf\
    putty\
    pyright\
    python-pillow\
    python-pip\
    python-pyocd\
    python-pyqt5\
    python-pysmbc\
    python-reportlab\
    qalculate-gtk\
    qt5-imageformats\
    qt5-virtualkeyboard\
    qt5ct\
    qtcreator\
    qutebrowser\
    ranger\
    rdesktop\
    reaper\
    reiserfsprogs\
    remmina\
    ripgrep\
    riscv32-elf-binutils\
    rsync\
    ruby\
    rustup\
    s-nail\
    samba\
    sddm\
    sddm-breath-theme\
    sddm-kcm\
    sed\
    shadow\
    shell-color-scripts\
    shellcheck\
    skanlite\
    slock\
    sof-firmware\
    spectacle\
    spectre-meltdown-checker\
    sshfs\
    stack\
    steam\
    sudo\
    sunloginclient\
    sxiv\
    sysfsutils\
    system-config-printer\
    systemd\
    systemd-fsck-silent\
    systemd-kcm\
    systemd-sysvcompat\
    systemsettings\
    tar\
    terminus-font\
    texinfo\
    thefuck\
    thunderbird\
    timeshift\
    timeshift-autosnap-manjaro\
    tmux\
    traceroute\
    tree\
    ttf-dejavu\
    ttf-droid\
    ttf-inconsolata\
    ttf-indic-otf\
    ttf-jetbrains-mono\
    ttf-joypixels\
    ttf-liberation\
    ttf-meslo-nerd-font-powerlevel10k\
    ttf-ms-fonts\
    ttf-wps-fonts\
    udiskie\
    udisks2\
    unarchiver\
    unityhub\
    usb_modeswitch\
    usbutils\
    util-linux\
    uxplay\
    valgrind\
    verible-bin\
    vi\
    vim\
    virtualbox\
    visual-studio-code-bin\
    vlc\
    volumeicon\
    vulkan-extra-layers\
    vulkan-extra-tools\
    vulkan-html-docs\
    vulkan-validation-layers\
    wemeet-bin\
    wget\
    which\
    wine\
    wine-gecko\
    wine-mono\
    winetricks\
    wireless-regdb\
    wmctrl\
    wpa_supplicant\
    wps-office-cn\
    wps-office-mime-cn\
    wps-office-mui-zh-cn\
    x11vnc\
    xclip\
    xdg-desktop-portal-kde\
    xdg-user-dirs\
    xdg-utils\
    xdotool\
    xf86-input-elographics\
    xf86-input-evdev\
    xf86-input-libinput\
    xf86-input-void\
    xf86-video-amdgpu\
    xf86-video-intel\
    xf86-video-nouveau\
    xf86-video-qxl\
    xfsprogs\
    xmobar\
    xorg-mkfontscale\
    xorg-server\
    xorg-twm\
    xorg-xinit\
    xorg-xkill\
    xrdp\
    xz\
    yad\
    yakuake\
    yay\
    zathura\
    zathura-pdf-poppler\
    zoom\
    cargo-nextest\
    wezterm



